services:
  web:
    build: .
    container_name: guluz-container
    ports:
      - "5000:80"   # Tashqi port 5000, konteyner ichidagi 80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - guluz-net

  db:
    image: mysql:8.0
    container_name: guluz-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guluz_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - guluz-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: guluz-phpmyadmin
    restart: always
    ports:
      - "5001:80"   # Tashqi port 5001
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - guluz-net

networks:
  guluz-net:

volumes:
  db_data:
